### ISSUE TITLE
Consistent stall when constructing HammerLib on launch

### ISSUE THREAD

**Issue by danereinsch** [Krutoy242/Enigmatica2Expert-Extended#330] opened 2024-02-05 00:21 UTC
## Crash on first launch involving "Sending event FMLConstructionEvent to mod hammercore"

Have tried to launch the modpack for several versions now, and have gotten consistent timeouts during the initial load of the pack. Multiple versions of java have been used, including 1.8.0_401 and 1.8.0_349. This line has appeared on every crash log to date as the final line prior to the timeout.

**To Reproduce**

1. Download pack
2. Install either with or without Optifine
3. Launch pack
4. Timeout at HammerLib construction

**Modpack version** `v1.30.0`

**Screenshot**
![E2EE_Crash_HammerlibTimeout](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/74069925/84b226ae-23d9-4f6b-998a-cd813c7b2c3c)

**Debug Log**
![E2EE_Crash_Debug](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/74069925/1da3a794-0cf7-4f2a-804e-a874a2c2eb87)

**End of Minecraft Log through Prism**
![E2EE_Crash_2 4 24](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/74069925/0f566f87-5f25-427e-9ea1-ea5bed446033)

**Separate crash on startup**
(happened twice when trying to suss out the problem)
https://mclo.gs/uZCDYnx

Hoping to learn what the error is so that I can play the pack properly, have been looking forward to it since I saw the pack on CurseForge about a month ago. Unfortunately, this error has plagued me the entire time, no matter what java or driver updates I use. Thanks!

**Comment by Krutoy242** [comment] 2024-02-05 09:34
Thank you for the report!

I will investigate issue further.

**Comment by Krutoy242** [comment] 2024-02-05 09:42
Please send `logs/debug.log` file. You may need to enable generation of this file in your MC instance settings.

**Comment by mczph** [comment] 2024-02-14 04:16
Regarding this error, I have received report from players in my modpack a long time ago, but it is very rare, but you can try downgrading the [HammerCore/HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib) mod to [this version](https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/3611193)(There is no guarantee that the problem will be solved, and I didn't find anything in the mod's change log that might cause the problem)

**Comment by Krutoy242** [comment] 2024-02-14 06:52
> Regarding this error, I have received report from players in my modpack a long time ago, but it is very rare, but you can try downgrading the [HammerCore/HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib) mod to [this version](https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/3611193)(There is no guarantee that the problem will be solved, and I didn't find anything in the mod's change log that might cause the problem)

Thanks for the hint!

**Comment by Krutoy242** [comment] 2024-02-14 06:56
The issue could be also related to this config option: 
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/96f19fba-4d20-410b-86c3-cc0498768059)

**Comment by Krutoy242** [comment] 2024-02-14 15:15
> Alright so I've attempted to start the pack again with the suggested change, and now I'm getting this crash on load consistently: [mclo.gs/kpvDCXQ](https://mclo.gs/kpvDCXQ) . It _appears_ to be related to VertexLighterFlat, but I'm unsure.

Please double-check if you have mod duplicates in your `mods/` folder. It could be one of those mods:
```
ActuallyBaubles-1.12-1.1
architecturecraft-1.12-3.108
Avaritia-1.12.2-3.3.0.37-universal
Bedrock Ores-MC1.12-1.2.7.42
betteranimalsplusplus-4-13-2022b
BiomesOPlenty-1.12.2-7.0.1.2445-universal
Botania r1.10-364.4
botaniatweaks-1.9.1
cc-tweaked-1.12.2-1.89.2
ColossalChests-1.12.2-1.7.3
EnderIO-1.12.2-5.3.72
EndReborn [0.3.9]
ExCompressum_1.12.2-3.0.32
exnihilocreatio-1.12.2-0.4.7.2
forestry_1.12.2-5.8.2.422
iceandfire-1.9.1-1.12.2
ImmersiveCables-1.12.2-1.3.2
ImmersiveEngineering-0.12-98
industrialcraft-2-2.8.222-ex112
IntegratedCrafting-1.12.2-1.0.10
IntegratedDynamics-1.12.2-1.1.11
IntegratedTerminals-1.12.2-1.0.14
IntegratedTunnels-1.12.2-1.6.14
JustEnoughResources-1.12.2-0.9.2.60
LibVulpes-1.12.2-0.4.2-25-universal
MCTSmelteryIO-1.12.2-1.2.63
Mekanism-Community-Edition-1.12.2-9.12.8-Core
mia-1.12.2-0.2.2a
oeintegration-2.3.4
OldJavaWarning-1.12.2-1.1.11
OpenComputers-MC1.12.2-1.8.3+274990f
OpenTerrainGenerator-1.12.2-v9.5-R1
plethora-1.12.2-1.2.3
QuarkRotN-r1.6-188
RandomThings-MC1.12.2-4.2.7.4
rats-3.2.21-1.12.2
Requious Frakto-0.12
rustic-1.1.7
ScalingHealth-1.12.2-1.3.42+147
TConstruct-1.12.2-2.13.0.183
Thaumcraft-1.12.2-6.1.BETA26
thaumicwonders-1.8.2
thaumtweaks-0.3.5.3
ThermalDynamics-1.12.2-2.5.6.1-universal
ThermalExpansion-1.12.2-5.5.7.1-universal
ThermalInnovation-1.12.2-0.3.6.1-universal
TravelersBackpack-1.12.2-1.0.35
twilightforest-1.12.2-3.11.1021-universal
twilighttweaks-1.12.2-v1.0.2.jar
voidislandcontrol-1.5.3
xnet-1.12-1.8.2
```

**Comment by danereinsch** [comment] 2024-02-14 15:26
UPDATE: 
I've swapped out the included version of HammerCore/HammerLib to the one recommended by @mczph and it seems to work now! Thanks for the help y'all. Not sure why the updated file seems to not work properly, but I'm also not exactly an expert in this area. Additionally, I did not find any duplicated files in the mods folder, so I do not believe that was the cause. I feel pretty comfortable in saying that the HammerCore version or an interaction between it and (maybe) ArmoryExpansion or a different mod caused the crashes on startup.

> Regarding this error, I have received report from players in my modpack a long time ago, but it is very rare, but you can try downgrading the [HammerCore/HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib) mod to [this version](https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/3611193)(There is no guarantee that the problem will be solved, and I didn't find anything in the mod's change log that might cause the problem)

**Comment by Krutoy242** [comment] 2024-02-14 15:29
Good. I will consider to downgrade HammerCore then.

**Comment by mczph** [comment] 2024-02-15 02:53
Really a strange problem. It seems to only occur in a small part of PC environments.

**Comment by Krutoy242** [comment] 2024-02-17 10:08
> Regarding this error, I have received report from players in my modpack a long time ago, but it is very rare, but you can try downgrading the [HammerCore/HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib) mod to [this version](https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/3611193)(There is no guarantee that the problem will be solved, and I didn't find anything in the mod's change log that might cause the problem)

I just encountered same crash `NoClassDefFoundError: net/minecraftforge/client/model/pipeline/VertexLighterFlat` on mentioned version.

So I could only make assumption that `HammerLib` is not the reason or `HammerLib` version downgrade actually wont matter.
Log for history: https://mclo.gs/erRtL3i.

So, my other assumption that downgrading changing `mod count` / `mod versions` that causing re-creating of cache of some other mod, thus clearing erroring code.

I think, if @danereinsch will install `HammerLib-1.12.2-12.2.48` back his game will still load.

**Comment by Krutoy242** [comment] 2024-04-25 09:45
I suspect that this error caused by mod `sledgehammer` but cant reproduce. The error itself happens randomly and fixed by changing mod count / mod versions.

Since I cannot reproduce this issue and no players reported this issue last months, probably its happens very rare or fixed by mod updates. Also, looking to Discord history, 5 months ago some players fixed this issue by just restarting game.

So, i think i could close the issue. If someone will have this crash again, feel free to write here.

**Comment by Krutoy242** [comment] 2024-04-25 13:10
Reopen issue since new player reported same issue today https://mclo.gs/4lW4Dtf

**Comment by Krutoy242** [comment] 2024-06-14 12:41
Update:
Seems like SledgeHammer wasnt the reason because today i found a player who had error `NoClassDefFoundError: VertexLighterFlat` without SledgeHammer https://mclo.gs/TH8yjpr

**Comment by Krutoy242** [comment] 2024-08-15 09:48
Should be fixed in [next modpack version](https://www.curseforge.com/minecraft/mc-mods/hammer-lib) through this commit https://github.com/dragon-forge/HammerLib/commit/aeb705eaf3198d685c19b8a0db569b303af7d740

**Comment by Krutoy242** [comment] 2024-08-15 11:58
Should be fixed in https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v1.43.0

**Closed** 2024-08-15 11:58 UTC
Labels: bug
