### ISSUE TITLE
Crash: `java.lang.ArrayIndexOutOfBoundsException` when using JEI to look up molten iridium usages

### ISSUE THREAD

**Issue by alejandro-esquivel** [Krutoy242/Enigmatica2Expert-Extended#177] opened 2023-03-04 00:23 UTC
What the title says. The game sometimes crashes when opening Ice and Fire chests and when looking up some molten metals usages through JEI. [Here](https://mclo.gs/u6l0Bzn) is the log.

**Comment by Krutoy242** [comment] 2023-03-04 06:06
Thank you for report. I will investigate the issue.

What modpack version btw?

**Comment by Krutoy242** [comment] 2023-03-04 08:08
I cannot reproduce it. For me everything work fine.
Provide more information about modpack version please.

![javaw_XMNPw7MkBe](https://user-images.githubusercontent.com/936618/222884797-690b8389-8d68-4b14-a9e8-7c696cdc3b89.gif)

**Comment by alejandro-esquivel** [comment] 2023-03-04 15:24
The version is 0.89. It mostly happens whenever I open loot chests found in cyclops coves.

**Comment by Krutoy242** [comment] 2023-03-04 17:40
Thanks for the report anyway.
Most likely, this issue will be fixed next release.

**Comment by Krutoy242** [comment] 2023-03-26 06:52
Can you test if this happens on `v0.94.0` ?

**Comment by alejandro-esquivel** [comment] 2023-03-26 18:31
I'm still using 0.89 and now it started working fine again for some reason, the item that crashed the game no longer does so.

**Comment by alejandro-esquivel** [comment] 2023-03-26 18:32
I'm currently using GDLauncher and can't upgrade to 0.94, 0.89 is the last version available for me to play.

**Comment by Krutoy242** [comment] 2023-04-08 06:11
Can you upgrade to 1.0.0 right now and check if issue persist?

**Comment by Krutoy242** [comment] 2023-04-21 12:43
Since you not respond, probably issue resolved for you personally or becomes unrelated. I'm closing issue. Feel free to open new one if still actual.

**Closed** 2023-04-21 12:44 UTC
Labels: more-information-needed
