### ISSUE TITLE
Crash with Celestial Manipulator

### ISSUE THREAD

**Issue by Immortalis202** [Krutoy242/Enigmatica2Expert-Extended#418] opened 2024-09-21 22:16 UTC
Draconic Evolution Celestial Manipulator make the server crash with "io.netty.util.IllegalReferenceCountException: refCnt: 0" when used to change time on world

Use Celestial Manipulator and try to change time on server

**Modpack version** `v1.43

[crash-2024-09-21_15.48.24-server.txt](https://github.com/user-attachments/files/17085882/crash-2024-09-21_15.48.24-server.txt)

**Comment by Krutoy242** [comment] 2024-09-22 15:22
Thank you, i will investigate the issue.

**Comment by Krutoy242** [comment] 2024-09-22 16:01
I cannot reproduce the issue. Using `Celestial Manipulator` on server does not causing crash


https://github.com/user-attachments/assets/2a4fe9cb-5264-4373-96f2-8da895329b93

Is there any other mods you add or configs changed?

**Comment by Krutoy242** [comment] 2024-09-27 06:32
Please, test it in other dimension such as Overworld.

**Comment by Krutoy242** [comment] 2024-10-31 13:02
I still cannot reproduce this issue, even in Dimension 3.
Seems like this is one-time issue and caused by several non-related happenings.
Or maybe this is issue of one of the tweaking mods i updated recently, so issue is fixed now.

![image](https://github.com/user-attachments/assets/c3854203-dcb6-4b12-91e2-cf8741419edf)

**Closed by Krutoy242** 2024-10-31 13:02 UTC
