### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by tryingandtrying** [Krutoy242/Enigmatica2Expert-Extended#210] opened 2023-05-05 01:49 UTC
## Description

When playing the pack, the ram usage goes straight to the maximum.
(Possible side effect glass keeps randomly appearing in my world)

**To Reproduce**

1. Load world
2. Check task manager (or equivalent)
3. Ram at max
(To note: this is inconsistent, as sometimes the pack works properly)

 
**Screenshots**
![image](https://user-images.githubusercontent.com/126965355/236362575-0db3300a-8e96-4dc2-b68a-2e8e1a41a373.png)

**Modpack version** `v1.2.1`
(To note: I used to play in `v0.89.0` but when the exact same thing happened to my world I quit)

**Comment by Krutoy242** [comment] 2023-05-05 03:00
Thank you for report!
Yes, sadly, this issue reported by many players. Since it can't be easy reproducible, I'm still can't find mod that causing this issue.

**Comment by Krutoy242** [comment] 2023-05-07 09:00
I found that this happens when player **travel between dimensions**.

**Comment by tryingandtrying** [comment] 2023-05-08 06:08
Strange, considering I've had this issue when I reinstall the pack, make a new world, etc., so there might be multiple memory issues with the pack. I'd have to ask around and see if anybody else has an issue like mine or an issue like the one you describe.

**Comment by Krutoy242** [comment] 2023-05-13 10:05
Im still investigating this issue. Some people on [discord server](https://discord.gg/VcmyHdNNQP) says that this happens only with OTG world generator.

**Comment by Krutoy242** [comment] 2023-07-16 08:20
`Universal Tweaks` dev have released new version of his mod with [Fix Blood Magic memory leak](https://github.com/ACGaming/UniversalTweaks/commit/9d456f91044878e2aa3aa13d6f3e491c8013ee0a) feature. 

This may be related to our problem.
Can you test latest modpack version [v1.13.0](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v1.13.0) and see if problem still exist?

If you cant, i could ask other players to test that.

**Comment by Krutoy242** [comment] 2023-08-15 17:33
This bug probably fixed in version `v1.17.0`. If you still playing, please update and report if issue is fixed.

**Closed** 2023-08-31 12:36 UTC
Labels: bug
