### ISSUE TITLE
Fluid Pattern Terminal

### ISSUE THREAD

**Issue by siena1010** [Krutoy242/Enigmatica2Expert-Extended#417] opened 2024-09-20 22:54 UTC
When Fluid Pattern Terminal is in bauble slot (or even just if it is not in main hand) after opening it with hotkey i can't click on 'Crafting Status' or use auto-craft.

**Comment by Krutoy242** [comment] 2024-09-21 07:45
Thank you for the report.

Is this happen in single player world or on server?

**Comment by siena1010** [comment] 2024-09-21 09:01
on single player world

**Comment by Krutoy242** [comment] 2024-09-22 16:11
Yes, i can reproduce this issue on my client too.
Please remake this issue on AE2 github if it wasnt created already https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life
(i cant find their issue page actually 😐)

**Comment by Krutoy242** [comment] 2024-11-30 08:17
Closing this issue since [reported to AE2 tracker](https://github.com/AE2-UEL/Applied-Energistics-2/issues/511).

**Closed by Krutoy242** 2024-11-30 08:17 UTC
