### ISSUE TITLE
Brewing splash potions always brews splash potions of doom

### ISSUE THREAD

**Issue by DeleteMetaInf** [Krutoy242/Enigmatica2Expert-Extended#104] opened 2022-09-07 21:46 UTC
### Description

Creating splash potions by combining regular potions with gunpowder for some reason creates splash potions of doom from Extra Utilities 2, seemingly regardless of what splash potion you’re making. I attempted to make splash potions of healing and splash potions of harm, but trying to make either of those in a brewing stand resulted in me getting splash potions of doom instead. I followed the recipes, which are vanilla recipes, in Had Enough Items, and splash potions of doom, according to HEI, require potions of doom and no other potion, so it makes no sense that they were crafted this way. Definitely seems like a bug, since currently, you’re unable to brew splash potions because it always results in you getting splash potions of doom from EU2.

**Modpack version:** 0.69.0 (latest)

### To reproduce

Try to brew a splash potion.

**Comment by Krutoy242** [comment] 2022-09-08 05:13
Thank you for the report, but I this issue is duplicate of https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/79

**Closed** 2022-09-08 05:13 UTC

**Comment by DeleteMetaInf** [comment] 2022-09-08 15:54
@Krutoy242 Oh, I see. Is this going to be fixed? It's been a while since that issue was made.

**Comment by Krutoy242** [comment] 2022-09-08 17:49
Im still looking for solution since i dont know why its even broken this way.

**Comment by DeleteMetaInf** [comment] 2022-09-10 23:24
Maybe you can ask for help on the CT Discord. And maybe remove CT scripts until it doesn’t occur anymore, if the issue is caused by one of the CT scripts.

**Comment by Krutoy242** [comment] 2022-09-11 13:43
CT Discord usually ignore me or dont know answers 😅
And yes, if i remove any brewing tweaks - it fixes. But i cant let it be default brews recipes everywhere.
