### ISSUE TITLE
The composition of AE2 template cannot be made in the server

### ISSUE THREAD

**Issue by QQQQQQNB** [Krutoy242/Enigmatica2Expert-Extended#135] opened 2022-10-26 16:01 UTC
In fact, this is the case for many objects to make AE templates.
The recipe is correct, but the output items cannot be seen, and invalid templates are displayed
However, stand-alone archiving does not have this problem. This problem only exists in the server
Sorry, my English is not good, I hope my words are easy to understand

**Comment by QQQQQQNB** [comment] 2022-10-26 16:07
![Uploading 42B62904-8295-45A0-9986-21160D62A520.jpeg…]()

**Comment by QQQQQQNB** [comment] 2022-10-26 16:17
Wait a minute. I'm studying. I don't know why I can't upload pictures

**Comment by QQQQQQNB** [comment] 2022-10-26 16:38
Uploading 68849503833__7B72CA81-17EA-4C22-8494-DF3876F7986E.MOV…

**Comment by QQQQQQNB** [comment] 2022-10-26 16:48
Sorry, could you tell me your email address? I think it's my network problem or VPN problem. I can't upload pictures or videos here, nor can I upload pictures in the curseforge comment area.

**Comment by Krutoy242** [comment] 2022-10-26 19:26
Try to use image hosting like https://imgur.com/

**Comment by QQQQQQNB** [comment] 2022-10-27 03:39
https://imgur.com/gallery/c7UpD0E

OK.sorry,I'm sleeping because of jet lag. I have passed on the pictures for a long time. In fact, many objects are made in this way. 《thermal》 machine, 《AE2》 64K, 16K, etc

**Comment by Krutoy242** [comment] 2022-10-27 06:01
Oh, now I see.
What modpack version you play on?

**Comment by QQQQQQNB** [comment] 2022-10-27 06:16
0.73.0

**Comment by Krutoy242** [comment] 2022-10-27 07:44
Thank you. I will take a look at it.

**Comment by Krutoy242** [comment] 2022-11-09 07:45
Seems like problem was related to AE2 mod and already fixed in new versions.
I cant reproduce issue and its working fine on my side. Even autocrafting works fine

![image](https://user-images.githubusercontent.com/936618/200768762-608b7f4a-0064-4921-b823-eb116390770d.png)

Feel free to write into this issue if problem still actual!

**Closed by Krutoy242** 2022-11-09 07:45 UTC
Labels: bug
